schema_version: 1

context:
  name: row
  version: "1.0.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/glotzerlab/${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}.tar.zst
  sha256: cd791d6b10d31cf1c768c148dd781322a3223833849809f1e45b2f13c2be95a5

build:
  number: 1
  skip: true  # [win]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --locked --no-track --root "${PREFIX}" --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses
  host:
  run:

tests:
  - script:
    - row --version
  - script:
    - row show cluster
  - script:
    - row show launchers

about:
  homepage: https://glotzerlab.engin.umich.edu
  summary: Row is a command line tool that helps you manage workflows on HPC resources.
  description: |
    Row is a command line tool that helps you manage workflows on HPC resources. Define
    **actions** in a workflow configuration file that apply to **groups** of **directories**
    in your **workspace**. **Submit** actions to your cluster's **scheduler**. Row tracks
    which actions have been submitted on which directories so that you don't submit the same
    work twice. Once a job completes, subsequent actions become eligible allowing you to
    process your entire workflow to completion over many submissions.  
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://row.readthedocs.io/
  repository: https://github.com/glotzerlab/row

extra:
  recipe-maintainers:
    - joaander
    - tcmoore3
